### ISSUE TITLE
Using sort() that is deprecated in Pandas.

### ISSUE THREAD

**Issue by edwardmoradian** [DanaJomar/PyALE#10]
I ran into the issue of a newer version of Pandas that uses sort_values or sort_index for sort (deprecated in 2017).  In PyALE\_src\ALE_1D.py, sort is being called in line 96.  Can we switch to the newer function sort_values?  In other lines of the program, lines 61 and 221, sort_values and sort_index are being used.  I am getting an error, "AttributeError: 'Categorical' object has no attribute 'sort'".

Issue Code Line 95 and 96:
  groups = X[feature].unique()
  groups.sort()

**Comment by DanaJomar** [comment]
Hi [edwardmoradian](https://github.com/edwardmoradian), 
groups is a numpy array (the output of [`unique`](https://pandas.pydata.org/docs/reference/api/pandas.Series.unique.html)) so the function `sort` in this location is not supposed to be pandas deprecated sort.   
can you please provide a reproducible example of the error you got so I can take a deeper look into it?

**Comment by edwardmoradian** [comment]
Thanks for the clarification.  Looks like unique() is returning a Categorical dtype for me instead of the ndarray. I need to manipulate my data.
