### ISSUE TITLE
The image cannot be displayed

### ISSUE THREAD

**Issue by jiayubo6** [DanaJomar/PyALE#11]
Hello,
When I run the code in the example, the window does not display an image. 
My python version is 3.9. is it the problem with the version?
Thanks

**Comment by DanaJomar** [comment]
Hi there,
are you running the notebook as is, or are you running the code snippets somewhere else?
if you are running the notebook with jupyter, try adding `%matplotlib inline` in the first cell after the imports and try again, if this fixes your problem then you probably need to update your ipykernel (current latest version 6.21.1)
