### ISSUE TITLE
How do I output the values for the x and y axes

### ISSUE THREAD

**Issue by LongYistar** [DanaJomar/PyALE#25]
I want to know how to output the x and y values, or how to place multiple graphs on a single layout, which I'm confused about and I don't fit well with matplotlib

**Comment by DanaJomar** [comment]
Hello there, 
sorry for the late reply. I hope it still helps.

actually the function `ale` returns everything you need to make your own plot.
the index is the x axis, and the effects `eff` are the values of the y axis:

![image](https://github.com/DanaJomar/PyALE/assets/42438529/7b2347d6-d572-4bc9-b60f-b55bfd12514e)

Take a look at the examples in https://github.com/DanaJomar/PyALE/tree/master/examples, specifically in [Examples.ipynb](https://github.com/DanaJomar/PyALE/blob/master/examples/Examples.ipynb) there is an example on how you can give the function `ale`  your own matplotlib figure and axis, which will enable you to customize your plots (in the examples file search for **customizable plotting**)
