### ISSUE TITLE
Bugs in aleplot_1d_discrete?

### ISSUE THREAD

**Issue by aj11235** [DanaJomar/PyALE#3]
I believe I've come across two small bugs in the aleplot_1d_discrete function through my use of PyALE:

1. Line 99        feature_codes = X[feature].replace(groups_codes)
I've had this return an array of floats rather than ints, which then caused the code to fail when trying to use feature_codes as array indices in 
Line 116        X_plus.loc[ind_plus, feature] = groups[feature_codes[ind_plus] + 1]
Appending **.astype(int)** to .replace(groups_codes) fixed this problem for me.
2. When evaluating a Keras model that returned an array with a singleton dimension,
Line 121        y_hat = model.predict(X)
Line 122        y_hat_plus = model.predict(X_plus[ind_plus])
Line 123        y_hat_neg = model.predict(X_neg[ind_neg])
Lead to errors when trying to create dataframes in
Line 136        pd.DataFrame({"eff": Delta_plus, feature: groups[feature_codes[ind_plus] + 1]}),
Line 137        pd.DataFrame({"eff": Delta_neg, feature: groups[feature_codes[ind_neg]]}),
Appending **.ravel()** to the three model.predict() calls fixed this problem for me.

**Comment by DanaJomar** [comment]
Thank you for taking the time for reporting these issues, I'll take a closer look at them and release a fix as soon as possible. I would appriciate it if you can provide a minimal reproducible example to replicate the issue on my side.

**Comment by DanaJomar** [comment]
Fixed in release [v1.1.2](https://github.com/DanaJomar/PyALE/releases/tag/v1.1.2)
