### ISSUE TITLE
What is the meaning of the small scale on the X axis?

### ISSUE THREAD

**Issue by ZuJinyan** [DanaJomar/PyALE#6]
I thought it was the distribution of observations at first, but when I changed the grid size I found that they changed as well.

**Comment by DanaJomar** [comment]
yes that is the distribution of the observations, however it has a jitter effect that is dependant on the grid size to make sure that a point doesn't wander way off its containing bin. 
But I do think you have a point here, I'll keep this issue open I might do something about it in a future release. Thank you for bringing this to my attention.

**Comment by ZuJinyan** [comment]
I see, thank you very much for your reply! Have a nice day!

Jinyan ZU
________________________________
