### ISSUE TITLE
How to cite?

### ISSUE THREAD

**Issue by dionhaefner** [DanaJomar/PyALE#7]
I am using PyALE in a scientific publication. Do you have a preferred way how I should cite the project?

**Comment by DanaJomar** [comment]
Hi Dion, thanks for asking.
As far as I know with BibTeX the tag `@manual` is used for sofware citations, so here's my suggestion, but feel free to change what doesn't fit your paper as long as the name of the package and link to the github page are there:
```
@manual{pyale2020,
    author = {Dana Jomar},
    title = {PyALE: A Python Implementation of Accumulated Local Effect Plots},
    year = 2020,
    publisher = {The Python Package Index (PyPI)},
    version  = {1.1.2},
    url = {https://github.com/DanaJomar/PyALE}
}
```
also I used the latest version in the entry but change that in case you used a different version
