### ISSUE TITLE
Missing values

### ISSUE THREAD

**Issue by jackobenco016** [DanaJomar/PyALE#9]
Hello,

Does the function take into account the missing values ?

Thanks

**Comment by DanaJomar** [comment]
Hi [jackobenco016](https://github.com/jackobenco016), 
in the current implementation no. The function uses the given model to predict with the given data, so the assumption is that the given data will not have missing values. If the data does contain missing values, I believe the function will tell you that the model can not predict with the given data (with the error message: `Please check that your model is fitted, and accepts X as input.`)
However do you have a case maybe where missing values should be specifically handled? I'll be happy to take a look and do some testing.

**Comment by DanaJomar** [comment]
Hi [jackobenco016](https://github.com/jackobenco016), 
in the current implementation no. The function uses the given model to predict with the given data, so the assumption is that the given data will not have missing values. If the data does contain missing values, I believe the function will tell you that the model can not predict with the given data (with the error message: `Please check that your model is fitted, and accepts X as input.`)
However do you have a case maybe where missing values should be specifically handled? I'll be happy to take a look and do some testing.

**Comment by solegalli** [comment]
I think missing data are taken care of (or not) by the model. For example, sklearn models won't accept missing data, therefore, we need to impute the data before training or obtaining predictions.

If you use something, else, like xgboost or catboost, and they train a model with NA, then they should be able to obtain the predictions with NA as well. 

I think the problem in the latter case would be, how to create meaningful ALE plots when for example a continuous variable has NA. I am not sure this has a theoretical solution though.
